# ---------- STAGE 1: Build ----------
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copy pom.xml and download the dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code and build the application
COPY src ./src
RUN mvn package -DskipTests

# ---------- STAGE 2: Runtime ----------
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copy the jar generated by the stage build
COPY --from=build /app/target/travel-emotions-*.jar app.jar

# Exposes port 8080
EXPOSE 8080

# App launch
ENTRYPOINT ["java", "-jar", "app.jar"]
